# Generated by Django 6.0.6 on 2026-07-04 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exterior_notes', models.TextField(blank=True)),
                ('has_dents', models.BooleanField(default=False)),
                ('has_scratches', models.BooleanField(default=False)),
                ('has_rust', models.BooleanField(default=False)),
                ('has_paint_damage', models.BooleanField(default=False)),
                ('has_cracked_glass', models.BooleanField(default=False)),
                ('has_missing_parts', models.BooleanField(default=False)),
                ('missing_parts_detail', models.TextField(blank=True)),
                ('interior_notes', models.TextField(blank=True)),
                ('has_damaged_seats', models.BooleanField(default=False)),
                ('has_bad_odor', models.BooleanField(default=False)),
                ('has_dashboard_warning', models.BooleanField(default=False)),
                ('dashboard_warning_detail', models.TextField(blank=True)),
                ('tire_condition', models.TextField(blank=True)),
                ('spare_tire_present', models.BooleanField(default=True)),
                ('jack_present', models.BooleanField(default=True)),
                ('mileage_in', models.IntegerField(blank=True, null=True)),
                ('fuel_level', models.CharField(blank=True, max_length=20)),
                ('documents_ok', models.BooleanField(default=True)),
                ('documents_notes', models.TextField(blank=True)),
                ('customer_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Inspección de recepción',
                'verbose_name_plural': 'Inspecciones de recepción',
            },
        ),
    ]
