# Generated by Django 5.0.6 on 2026-07-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_vehicleinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='mileage_unit',
            field=models.CharField(blank=True, default='KM', max_length=10),
        ),
    ]
