# Generated by Django 5.0.6 on 2026-07-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0003_vehicleinspection_mileage_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='light_high_left_ok',
            field=models.BooleanField(default=True, verbose_name='Luz alta izquierda'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='light_high_right_ok',
            field=models.BooleanField(default=True, verbose_name='Luz alta derecha'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='light_low_left_ok',
            field=models.BooleanField(default=True, verbose_name='Luz baja izquierda'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='light_low_right_ok',
            field=models.BooleanField(default=True, verbose_name='Luz baja derecha'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='light_medium_left_ok',
            field=models.BooleanField(default=True, verbose_name='Luz media izquierda'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='light_medium_right_ok',
            field=models.BooleanField(default=True, verbose_name='Luz media derecha'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='light_plate_front_ok',
            field=models.BooleanField(default=True, verbose_name='Luz de placa adelante'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='light_plate_rear_ok',
            field=models.BooleanField(default=True, verbose_name='Luz de placa atrás'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='light_turn_left_ok',
            field=models.BooleanField(default=True, verbose_name='Luces de giro izquierda'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='light_turn_right_ok',
            field=models.BooleanField(default=True, verbose_name='Luces de giro derecha'),
        ),
    ]
