# Generated by Django 5.0.6 on 2026-07-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_vehicleinspection_light_high_left_ok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='glass_left_front_ok',
            field=models.BooleanField(default=True, verbose_name='Vidrio puerta delantera izq.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='glass_left_quarter_ok',
            field=models.BooleanField(default=True, verbose_name='Ventilete trasero izq.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='glass_left_rear_ok',
            field=models.BooleanField(default=True, verbose_name='Vidrio puerta trasera izq.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='glass_notes',
            field=models.TextField(blank=True, verbose_name='Notas de vidrios'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='glass_rear_ok',
            field=models.BooleanField(default=True, verbose_name='Trasero'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='glass_right_front_ok',
            field=models.BooleanField(default=True, verbose_name='Vidrio puerta delantera der.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='glass_right_quarter_ok',
            field=models.BooleanField(default=True, verbose_name='Ventilete trasero der.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='glass_right_rear_ok',
            field=models.BooleanField(default=True, verbose_name='Vidrio puerta trasera der.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='glass_windshield_ok',
            field=models.BooleanField(default=True, verbose_name='Parabrisas delantero'),
        ),
    ]
