# Generated by Django 5.0.6 on 2026-07-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0005_vehicleinspection_glass_left_front_ok_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='has_cracked_glass',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='has_dents',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='has_missing_parts',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='has_paint_damage',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='has_rust',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='has_scratches',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='missing_parts_detail',
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_antenna_ok',
            field=models.BooleanField(default=True, verbose_name='Antena de radio'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_bumper_front_ok',
            field=models.BooleanField(default=True, verbose_name='Parachoque delantero'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_bumper_rear_ok',
            field=models.BooleanField(default=True, verbose_name='Parachoque trasero'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_dents_detail',
            field=models.TextField(blank=True, verbose_name='Abolladuras'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_gas_cap_ok',
            field=models.BooleanField(default=True, verbose_name='Tapa de gasolina'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_mirror_left_ok',
            field=models.BooleanField(default=True, verbose_name='Espejo lateral izq.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_mirror_right_ok',
            field=models.BooleanField(default=True, verbose_name='Espejo lateral der.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_plate_front_ok',
            field=models.BooleanField(default=True, verbose_name='Placa adelante'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_plate_rear_ok',
            field=models.BooleanField(default=True, verbose_name='Placa atrás'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_scratches_detail',
            field=models.TextField(blank=True, verbose_name='Rayones'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_wheel_cap_left_front_ok',
            field=models.BooleanField(default=True, verbose_name='Tapón rueda izq. del.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_wheel_cap_left_rear_ok',
            field=models.BooleanField(default=True, verbose_name='Tapón rueda izq. tras.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_wheel_cap_right_front_ok',
            field=models.BooleanField(default=True, verbose_name='Tapón rueda der. del.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_wheel_cap_right_rear_ok',
            field=models.BooleanField(default=True, verbose_name='Tapón rueda der. tras.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_wiper_front_left_ok',
            field=models.BooleanField(default=True, verbose_name='Limpiaparabrisas del. izq.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_wiper_front_right_ok',
            field=models.BooleanField(default=True, verbose_name='Limpiaparabrisas del. der.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='exterior_wiper_rear_ok',
            field=models.BooleanField(default=True, verbose_name='Limpiaparabrisas trasero'),
        ),
    ]
