# Generated by Django 5.0.6 on 2026-07-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0006_remove_vehicleinspection_has_cracked_glass_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='dashboard_warning_detail',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='has_bad_odor',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='has_damaged_seats',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='has_dashboard_warning',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='jack_present',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='spare_tire_present',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='tire_condition',
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_cigarette_lighter_ok',
            field=models.BooleanField(default=True, verbose_name='Cigarrera'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_door_pull_lf_ok',
            field=models.BooleanField(default=True, verbose_name='Jalador izq. del.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_door_pull_lr_ok',
            field=models.BooleanField(default=True, verbose_name='Jalador izq. tras.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_door_pull_rf_ok',
            field=models.BooleanField(default=True, verbose_name='Jalador der. del.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_door_pull_rr_ok',
            field=models.BooleanField(default=True, verbose_name='Jalador der. tras.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_extinguisher_ok',
            field=models.BooleanField(default=True, verbose_name='Extintor'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_floor_mats_ok',
            field=models.BooleanField(default=True, verbose_name='Tapetes'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_floor_ok',
            field=models.BooleanField(default=True, verbose_name='Pisos'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_floor_type',
            field=models.CharField(blank=True, default='alfombra', max_length=20, verbose_name='Tipo piso'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_grab_handle_lf_ok',
            field=models.BooleanField(default=True, verbose_name='Sujetador izq. del.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_grab_handle_lr_ok',
            field=models.BooleanField(default=True, verbose_name='Sujetador izq. tras.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_grab_handle_rf_ok',
            field=models.BooleanField(default=True, verbose_name='Sujetador der. del.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_grab_handle_rr_ok',
            field=models.BooleanField(default=True, verbose_name='Sujetador der. tras.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_horn_ok',
            field=models.BooleanField(default=True, verbose_name='Bocina'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_jack_ok',
            field=models.BooleanField(default=True, verbose_name='Gata'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_radio_cd_dvd',
            field=models.BooleanField(default=True, verbose_name='CD/DVD'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_radio_ok',
            field=models.BooleanField(default=True, verbose_name='Radio'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_radio_screen',
            field=models.BooleanField(default=True, verbose_name='Pantalla'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_rearview_mirror_ok',
            field=models.BooleanField(default=True, verbose_name='Retrovisor'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_seat_covers_front_ok',
            field=models.BooleanField(default=True, verbose_name='Fundas delanteras'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_seat_covers_rear_ok',
            field=models.BooleanField(default=True, verbose_name='Fundas traseras'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_seatbelts_ok',
            field=models.BooleanField(default=True, verbose_name='Cinturones'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_spare_tire_ok',
            field=models.BooleanField(default=True, verbose_name='Llanta auxilio'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_triangles_ok',
            field=models.BooleanField(default=True, verbose_name='Triángulos seguridad'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_window_handle_lf_ok',
            field=models.BooleanField(default=True, verbose_name='Manija vidrio izq. del.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_window_handle_lr_ok',
            field=models.BooleanField(default=True, verbose_name='Manija vidrio izq. tras.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_window_handle_rf_ok',
            field=models.BooleanField(default=True, verbose_name='Manija vidrio der. del.'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='interior_window_handle_rr_ok',
            field=models.BooleanField(default=True, verbose_name='Manija vidrio der. tras.'),
        ),
    ]
