# Generated by Django 5.0.6 on 2026-08-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0007_remove_vehicleinspection_dashboard_warning_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='initial_diagnosis',
            field=models.TextField(blank=True, verbose_name='Diagnóstico inicial del mecánico'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='reported_problem',
            field=models.TextField(blank=True, verbose_name='Problema reportado por el propietario'),
        ),
    ]
