# Generated by Django 5.0.6 on 2026-08-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0008_workorder_initial_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio de trabajo'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de facturación'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de conclusión'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
