# Generated by Django 5.0.6 on 2026-08-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0009_workorder_assigned_at_workorder_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='checklist_caps_ok',
            field=models.BooleanField(default=False, verbose_name='Tapas de depósitos de líquidos y aceites revisadas'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='checklist_fasteners_ok',
            field=models.BooleanField(default=False, verbose_name='Ajuste de pernos, tornillos y abrazaderas realizado'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='checklist_fluids_ok',
            field=models.BooleanField(default=False, verbose_name='Niveles de líquidos y aceites revisados'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='checklist_lug_nuts_ok',
            field=models.BooleanField(default=False, verbose_name='Ajuste de tuercas y ruedas realizado'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='mechanic_observations',
            field=models.TextField(blank=True, verbose_name='Observaciones del mecánico'),
        ),
    ]
