# Generated by Django 6.0.6 on 2026-07-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ci',
            field=models.CharField(default='', max_length=50, verbose_name='CI'),
        ),
    ]
