# Generated by Django 6.0.6 on 2026-07-04 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ServiceVehiclePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('automovil', 'Automóvil'), ('vagoneta', 'Vagoneta'), ('camioneta', 'Camioneta'), ('camion', 'Camión'), ('trufi', 'Trufi'), ('micro', 'Micro')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_prices', to='service_catalog.service')),
            ],
            options={
                'verbose_name': 'Precio por tipo de vehículo',
                'verbose_name_plural': 'Precios por tipo de vehículo',
                'unique_together': {('service', 'vehicle_type')},
            },
        ),
    ]
