# Generated by Django 5.0.6 on 2026-07-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_catalog', '0002_alter_service_price_servicevehicleprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevehicleprice',
            name='vehicle_type',
            field=models.CharField(max_length=50),
        ),
    ]
