# Generated by Django 6.0.6 on 2026-07-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ci_nit',
            field=models.CharField(blank=True, max_length=50, verbose_name='CI/NIT'),
        ),
    ]
