# Generated by Django 6.0.6 on 2026-07-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_ci_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('automovil', 'Automóvil'), ('vagoneta', 'Vagoneta'), ('camioneta', 'Camioneta'), ('camion', 'Camión'), ('trufi', 'Trufi'), ('micro', 'Micro')], default='automovil', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ci_nit',
            field=models.CharField(max_length=50, verbose_name='CI/NIT'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('nissan', 'Nissan'), ('suzuki', 'Suzuki'), ('honda', 'Honda'), ('chevrolet', 'Chevrolet'), ('ford', 'Ford'), ('volkswagen', 'Volkswagen'), ('bmw', 'BMW'), ('mercedes_benz', 'Mercedes-Benz'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('mazda', 'Mazda'), ('mitsubishi', 'Mitsubishi'), ('renault', 'Renault'), ('peugeot', 'Peugeot'), ('fiat', 'Fiat'), ('jeep', 'Jeep'), ('dodge', 'Dodge'), ('subaru', 'Subaru'), ('volvo', 'Volvo'), ('audi', 'Audi'), ('lexus', 'Lexus'), ('jaguar', 'Jaguar'), ('land_rover', 'Land Rover'), ('mini', 'Mini'), ('porsche', 'Porsche'), ('otro', 'Otro')], max_length=30),
        ),
    ]
