# Generated by Django 5.0.6 on 2026-07-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_vehicle_vehicle_type_alter_customer_ci_nit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('nissan', 'Nissan'), ('suzuki', 'Suzuki'), ('honda', 'Honda'), ('chevrolet', 'Chevrolet'), ('ford', 'Ford'), ('volkswagen', 'Volkswagen'), ('bmw', 'BMW'), ('mercedes_benz', 'Mercedes-Benz'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('mazda', 'Mazda'), ('mitsubishi', 'Mitsubishi'), ('renault', 'Renault'), ('peugeot', 'Peugeot'), ('fiat', 'Fiat'), ('jeep', 'Jeep'), ('dodge', 'Dodge'), ('subaru', 'Subaru'), ('volvo', 'Volvo'), ('audi', 'Audi'), ('lexus', 'Lexus'), ('jaguar', 'Jaguar'), ('land_rover', 'Land Rover'), ('mini', 'Mini'), ('porsche', 'Porsche'), ('otro', 'Otro'), ('acura', 'Acura'), ('alfa_romeo', 'Alfa Romeo'), ('aston_martin', 'Aston Martin'), ('bentley', 'Bentley'), ('buick', 'Buick'), ('cadillac', 'Cadillac'), ('chery', 'Chery'), ('chrysler', 'Chrysler'), ('citroen', 'Citroën'), ('dacia', 'Dacia'), ('daewoo', 'Daewoo'), ('daihatsu', 'Daihatsu'), ('ferrari', 'Ferrari'), ('gac', 'GAC'), ('geely', 'Geely'), ('gmc', 'GMC'), ('great_wall', 'Great Wall'), ('haval', 'Haval'), ('hummer', 'Hummer'), ('infiniti', 'Infiniti'), ('isuzu', 'Isuzu'), ('iveco', 'Iveco'), ('jac', 'JAC'), ('lamborghini', 'Lamborghini'), ('lancia', 'Lancia'), ('lincoln', 'Lincoln'), ('lotus', 'Lotus'), ('maserati', 'Maserati'), ('mclaren', 'McLaren'), ('mg', 'MG'), ('morris', 'Morris'), ('opel', 'Opel'), ('rolls_royce', 'Rolls-Royce'), ('saab', 'Saab'), ('seat', 'SEAT'), ('skoda', 'Škoda'), ('smart', 'Smart'), ('ssangyong', 'SsangYong'), ('tesla', 'Tesla'), ('vauxhall', 'Vauxhall')], max_length=50),
        ),
    ]
