# Generated by Django 5.0.6 on 2026-07-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_vehicle_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
    ]
